module.exports = {
  generalSidebar: [
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: "Guides/Getting-Started/getting-started"},
      items: [
        "Guides/Getting-Started/file-formats",
        "Guides/Getting-Started/command-line",
        "Guides/Getting-Started/color-guide",
      ],
    },
    "Guides/tool-index",
    {
      type: 'category',
      label: 'Tutorials',
      // link: {type: 'doc', id: "/path/to/doc"},
      items: [
        "Guides/Tutorials/chipexo-tutorial",
        "Guides/Tutorials/genomic-features-tutorial",
        "Guides/Tutorials/genome-tracks-tutorial",
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      // link: {type: 'doc', id: "/path/to/doc"},
      items : [
        "Guides/Contributing/developer-guidelines",
        "Guides/Contributing/code-snippets",
        "Guides/Contributing/testing",
      ],
    },
    {
      type: 'category',
      label: 'Community',
      // link: {type: 'doc', id: "/path/to/doc"},
      items: [
        "Guides/Community/code-of-conduct"
      ],
    },
    "Guides/citing-us",
  ],
  toolSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Tools',
    },
  ],
};
