module.exports = {
  generalSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Guides',
    },
  ],
  tutorialsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Tutorials',
    },
  ],
  toolSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Tools',
    },
  ],
};
