module.exports = {
  generalSidebar: {
    Guides: [
      "Guides/getting-started",
      "Guides/command-line",
      "Guides/color-guide",
    ],
    Tutorials: [
      "Tutorials/chipexo-tutorial",
      "Tutorials/genomic-features-tutorial",
      "Tutorials/genome-tracks-tutorial",
    ],
    References: [
      "References/file-formats",
      "References/tool-index",
      "References/publications",
    ],
    Contributing: [
      "Contributing/developer-guidelines",
      "Contributing/code-snippets",
      "Contributing/testing",
    ],
    Community: ["Community/code-of-conduct"],
  },
  toolSidebar: [
    {
      type: 'autogenerated',
      dirName: 'Tools',
    },
  ],
};
